'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, Bookmark, Check, ChevronDown, Clock3, ExternalLink, Filter, Heart, MapPin, Search, Sparkles, X } from 'lucide-react'
import { interests, opportunities, types, type Opportunity } from '@/lib/data'

type View = 'discover' | 'saved' | 'profile' | 'detail'
const event = (name: string, opportunityId?: string) => { if (typeof window !== 'undefined') { const events = JSON.parse(localStorage.getItem('campusfind_events') || '[]'); events.push({ name, opportunityId, timestamp: new Date().toISOString() }); localStorage.setItem('campusfind_events', JSON.stringify(events)) } }

export default function Home() {
  const [view, setView] = useState<View>('discover')
  const [selected, setSelected] = useState<Opportunity | null>(null)
  const [saved, setSaved] = useState<string[]>([])
  const [applied, setApplied] = useState<string[]>([])
  const [activeType, setActiveType] = useState('All opportunities')
  const [search, setSearch] = useState('')
  const [showFilter, setShowFilter] = useState(false)
  const [onboarding, setOnboarding] = useState(false)
  const [onboardStep, setOnboardStep] = useState(0)
  const [selectedInterests, setSelectedInterests] = useState<string[]>(['Artificial Intelligence', 'Product Management'])
  const [selectedTypes, setSelectedTypes] = useState<string[]>(['Research', 'Hackathon', 'Fellowship'])
  useEffect(() => { setSaved(JSON.parse(localStorage.getItem('campusfind_saved') || '[]')); setApplied(JSON.parse(localStorage.getItem('campusfind_applied') || '[]')) }, [])
  const filtered = useMemo(() => opportunities.filter(o => (activeType === 'All opportunities' || o.type === activeType) && `${o.title} ${o.organization} ${o.tags.join(' ')}`.toLowerCase().includes(search.toLowerCase())), [activeType, search])
  const toggleSaved = (id: string) => { const next = saved.includes(id) ? saved.filter(x => x !== id) : [...saved, id]; setSaved(next); localStorage.setItem('campusfind_saved', JSON.stringify(next)); event(saved.includes(id) ? 'opportunity_unsaved' : 'opportunity_saved', id) }
  const open = (o: Opportunity) => { setSelected(o); setView('detail'); event('opportunity_opened', o.id) }
  const toggleApplied = (id: string) => { const next = applied.includes(id) ? applied.filter(x => x !== id) : [...applied, id]; setApplied(next); localStorage.setItem('campusfind_applied', JSON.stringify(next)); event('marked_applied', id) }

  if (onboarding) return <Onboarding step={onboardStep} setStep={setOnboardStep} interests={selectedInterests} setInterests={setSelectedInterests} chosenTypes={selectedTypes} setTypes={setSelectedTypes} finish={() => { setOnboarding(false); event('onboarding_completed') }} />
  return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark"><Sparkles size={15} /></span><span>CampusFind</span></div><p className="workspace-label">YOUR CAMPUS</p><nav><Nav active={view === 'discover'} icon="✦" label="Discover" onClick={() => setView('discover')} count="12" /><Nav active={view === 'saved'} icon="♡" label="Saved" onClick={() => setView('saved')} count={saved.length ? String(saved.length) : undefined} /><Nav active={view === 'profile'} icon="◌" label="Profile" onClick={() => setView('profile')} /></nav><div className="sidebar-bottom"><div className="mini-user"><span className="avatar">AL</span><div><strong>Alex Lee</strong><small>Carnegie Mellon</small></div><ChevronDown size={15} /></div></div></aside><section className="content"><header className="topbar"><div className="crumb">Fall 2024 <span>·</span> Carnegie Mellon</div><div className="top-actions"><button className="icon-btn" aria-label="Search"><Search size={18} /></button><button className="avatar avatar-top" onClick={() => setView('profile')}>AL</button></div></header>{view === 'discover' && <Discover filtered={filtered} activeType={activeType} setActiveType={(v) => { setActiveType(v); event('filter_applied') }} search={search} setSearch={setSearch} showFilter={showFilter} setShowFilter={setShowFilter} saved={saved} toggleSaved={toggleSaved} open={open} startOnboarding={() => setOnboarding(true)} />}{view === 'saved' && <Saved saved={saved} applied={applied} toggleSaved={toggleSaved} toggleApplied={toggleApplied} open={open} />}{view === 'detail' && selected && <Detail opportunity={selected} saved={saved} applied={applied} toggleSaved={toggleSaved} toggleApplied={toggleApplied} back={() => setView('discover')} />}{view === 'profile' && <Profile interests={selectedInterests} types={selectedTypes} edit={() => { setOnboardStep(0); setOnboarding(true) }} />}</section></main>
}

function Nav({ active, icon, label, onClick, count }: { active: boolean; icon: string; label: string; onClick: () => void; count?: string }) { return <button className={`nav-item ${active ? 'active' : ''}`} onClick={onClick}><span className="nav-icon">{icon}</span>{label}{count && <span className="nav-count">{count}</span>}</button> }
function Discover({ filtered, activeType, setActiveType, search, setSearch, showFilter, setShowFilter, saved, toggleSaved, open, startOnboarding }: any) { return <div className="page"><div className="page-heading"><div><p className="eyebrow">PERSONALIZED FOR YOU</p><h1>Opportunities worth<br /><em>your time.</em></h1><p className="lede">A short list of things you might actually want to do.</p></div><button className="secondary-btn" onClick={startOnboarding}>Edit preferences <ArrowRight size={16} /></button></div><div className="insight"><div className="insight-icon"><Sparkles size={18} /></div><div><strong>Your feed is looking good.</strong><span>We found {filtered.length + 7} opportunities matching your interests and preferences.</span></div><button aria-label="Dismiss"><X size={16} /></button></div><div className="toolbar"><div className="filters">{['All opportunities', 'Research', 'Events', 'Hackathon', 'Clubs'].map((type) => <button key={type} className={activeType === type ? 'filter active' : 'filter'} onClick={() => setActiveType(type)}>{type === 'All opportunities' ? 'All' : type}</button>)}<button className="filter more" onClick={() => setShowFilter(!showFilter)}><Filter size={14} /> More filters</button></div><div className="search-box"><Search size={15} /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Search opportunities" /></div></div>{showFilter && <div className="filter-panel"><span>Sort by</span><button className="selected-pill">Best match <Check size={13} /></button><button>Deadline soon</button><button>Newest</button></div>}<div className="feed-meta"><span><strong>{filtered.length}</strong> opportunities for you</span><span className="updated">Updated just now</span></div><div className="opportunity-list">{filtered.map((o: Opportunity, i: number) => <OpportunityCard key={o.id} o={o} saved={saved.includes(o.id)} toggleSaved={toggleSaved} open={open} featured={i === 0} />)}{filtered.length === 0 && <div className="empty"><div className="empty-icon">⌕</div><h3>No opportunities found</h3><p>Try a different search or clear your filters.</p></div>}</div></div> }
function OpportunityCard({ o, saved, toggleSaved, open, featured }: { o: Opportunity; saved: boolean; toggleSaved: (id: string) => void; open: (o: Opportunity) => void; featured?: boolean }) { return <article className={`opportunity-card ${featured ? 'featured' : ''}`}><div className={`card-accent ${o.accent}`} /><div className="card-body"><div className="card-top"><span className="type-label">{o.type}</span><span className="match"><span className="match-dot">✦</span> {o.score}% match</span></div><h2>{o.title}</h2><p className="org">{o.organization}</p><p className="description">{o.description}</p><div className="tag-row">{o.tags.map(t => <span key={t} className="tag">{t}</span>)}</div><div className="why"><span className="why-label">WHY THIS MATCHES</span><span>{o.why.join('  ·  ')}</span></div><div className="card-footer"><span className={o.urgency ? 'deadline urgent' : 'deadline'}><Clock3 size={14} /> Deadline {o.deadline} {o.urgency && <b>· {o.urgency}</b>}</span><span className="commitment">{o.commitment}</span><div className="card-actions"><button className="text-btn" onClick={() => open(o)}>View opportunity <ArrowRight size={15} /></button><button className={`save-btn ${saved ? 'saved' : ''}`} onClick={() => toggleSaved(o.id)} aria-label={saved ? 'Unsave opportunity' : 'Save opportunity'}>{saved ? <Bookmark size={15} fill="currentColor" /> : <Heart size={15} />} {saved ? 'Saved' : 'Save'}</button></div></div></div></article> }
function Detail({ opportunity: o, saved, applied, toggleSaved, toggleApplied, back }: any) { return <div className="page detail-page"><button className="back-btn" onClick={back}><ArrowLeft size={16} /> Back to discover</button><div className="detail-layout"><article className="detail-main"><div className={`detail-banner ${o.accent}`}><span className="type-label">{o.type}</span><span className="match large"><span className="match-dot">✦</span> {o.score}% match</span></div><h1>{o.title}</h1><p className="detail-org">{o.organization}</p><div className="tag-row">{o.tags.map((t: string) => <span key={t} className="tag">{t}</span>)}</div><div className="why detail-why"><span className="why-label">WHY THIS MATCHES YOU</span>{o.why.map((w: string) => <span key={w}><Check size={14} /> {w}</span>)}</div><section className="detail-section"><h3>About this opportunity</h3><p>{o.details}</p></section><section className="detail-section"><h3>Eligibility</h3><p>{o.eligibility}</p></section><a className="source-note" href={o.sourceUrl} target="_blank">View original posting at {o.source} <ExternalLink size={14} /></a></article><aside className="detail-side"><div className="info-card"><InfoRow icon={<Clock3 />} label="Deadline" value={o.deadlineLabel} urgent={o.urgency} /><InfoRow icon={<MapPin />} label="Location" value={o.location} /><InfoRow icon={<Clock3 />} label="Time commitment" value={o.commitment} /><InfoRow icon={<Sparkles />} label="Compensation" value={o.compensation} /><InfoRow icon={<ExternalLink />} label="Source" value={o.source} /></div><div className="detail-cta"><button className={`primary-btn full ${saved.includes(o.id) ? 'saved-primary' : ''}`} onClick={() => toggleSaved(o.id)}><Bookmark size={17} fill={saved.includes(o.id) ? 'currentColor' : 'none'} /> {saved.includes(o.id) ? 'Saved' : 'Save opportunity'}</button><button className={`secondary-btn full ${applied.includes(o.id) ? 'applied' : ''}`} onClick={() => toggleApplied(o.id)}><Check size={17} /> {applied.includes(o.id) ? 'Marked applied' : 'Mark applied / registered'}</button><a className="original-btn" href={o.sourceUrl} target="_blank">View original / apply <ExternalLink size={15} /></a></div></aside></div></div> }
function InfoRow({ icon, label, value, urgent }: any) { return <div className="info-row"><span className="info-icon">{icon}</span><div><small>{label}</small><strong className={urgent ? 'urgent-text' : ''}>{value}</strong>{urgent && <small className="urgent-text">{urgent}</small>}</div></div> }
function Saved({ saved, applied, toggleSaved, toggleApplied, open }: any) { const savedItems = opportunities.filter(o => saved.includes(o.id)); const appliedItems = opportunities.filter(o => applied.includes(o.id)); return <div className="page"><div className="page-heading compact"><div><p className="eyebrow">YOUR SHORTLIST</p><h1>My opportunities.</h1><p className="lede">Keep the good ones close. Take action when you’re ready.</p></div></div><div className="saved-tabs"><span className="tab active">Saved <b>{savedItems.length}</b></span><span className="tab">Applied / Registered <b>{appliedItems.length}</b></span></div>{savedItems.length === 0 && appliedItems.length === 0 ? <div className="empty saved-empty"><div className="empty-icon">♡</div><h3>Your shortlist is empty</h3><p>Save opportunities from Discover and they’ll show up here.</p></div> : <div className="saved-list">{[...savedItems, ...appliedItems.filter(o => !saved.includes(o.id))].map(o => <div className="saved-row" key={o.id}><div className={`saved-dot ${o.accent}`} /><div className="saved-info"><span className="type-label">{o.type}</span><h3>{o.title}</h3><p>{o.organization}</p></div><div className="saved-deadline"><small>DEADLINE</small><strong className={o.urgency ? 'urgent-text' : ''}>{o.deadline}</strong><span>{o.urgency || 'Upcoming'}</span></div><div className="saved-actions"><button className="text-btn" onClick={() => open(o)}>View</button><button className={`mini-status ${applied.includes(o.id) ? 'done' : ''}`} onClick={() => toggleApplied(o.id)}>{applied.includes(o.id) ? <><Check size={14} /> Applied</> : 'Mark applied'}</button><button className="remove-btn" onClick={() => toggleSaved(o.id)} aria-label="Remove"><X size={16} /></button></div></div>)}</div>}</div> }
function Profile({ interests: selected, types: chosen, edit }: any) { return <div className="page profile-page"><div className="page-heading compact"><div><p className="eyebrow">YOUR PROFILE</p><h1>What you’re into.</h1><p className="lede">These preferences shape your Discover feed.</p></div><button className="secondary-btn" onClick={edit}>Edit preferences <ArrowRight size={16} /></button></div><div className="profile-card"><div className="profile-hero"><span className="avatar large-avatar">AL</span><div><h2>Alex Lee</h2><p>Carnegie Mellon University · Sophomore</p><span className="major">Information Systems</span></div></div><div className="profile-section"><h3>Interests</h3><div className="tag-row">{selected.map((x: string) => <span className="tag selected" key={x}>{x}</span>)}</div></div><div className="profile-section"><h3>Opportunity preferences</h3><div className="tag-row">{chosen.map((x: string) => <span className="tag selected" key={x}>{x}</span>)}</div></div></div></div> }
function Onboarding({ step, setStep, interests: selected, setInterests, chosenTypes, setTypes, finish }: any) { const stepCopy = [['First, tell us about you.', 'A little context helps us find opportunities that fit.', 'University'], ['What are you curious about?', 'Choose as many as you like. You can always change these later.', 'Your interests'], ['What do you want to see?', 'Pick the opportunity types that sound useful right now.', 'Your preferences']]; return <main className="onboarding"><div className="onboard-top"><div className="brand"><span className="brand-mark"><Sparkles size={15} /></span><span>CampusFind</span></div><span>Step {step + 1} of 3</span></div><div className="progress"><span style={{ width: `${((step + 1) / 3) * 100}%` }} /></div><div className="onboard-content"><p className="eyebrow">LET’S PERSONALIZE YOUR FEED</p><h1>{stepCopy[step][0]}</h1><p className="lede">{stepCopy[step][1]}</p>{step === 0 && <div className="form-stack"><label>{stepCopy[step][2]}<select defaultValue="Carnegie Mellon University"><option>Carnegie Mellon University</option><option>University of Pittsburgh</option><option>Other university</option></select></label><label>Academic year<select defaultValue="Sophomore"><option>Freshman</option><option>Sophomore</option><option>Junior</option><option>Senior</option></select></label><label>Major<input defaultValue="Information Systems" /></label></div>}{step === 1 && <div className="choice-grid">{interests.map(x => <button key={x} className={selected.includes(x) ? 'choice selected' : 'choice'} onClick={() => setInterests(selected.includes(x) ? selected.filter((i: string) => i !== x) : [...selected, x])}>{selected.includes(x) && <Check size={15} />}{x}</button>)}</div>}{step === 2 && <div className="choice-grid type-grid">{types.map(x => <button key={x} className={chosenTypes.includes(x) ? 'choice selected' : 'choice'} onClick={() => setTypes(chosenTypes.includes(x) ? chosenTypes.filter((i: string) => i !== x) : [...chosenTypes, x])}>{chosenTypes.includes(x) && <Check size={15} />}{x}</button>)}</div>}<div className="onboard-actions">{step > 0 && <button className="secondary-btn" onClick={() => setStep(step - 1)}>Back</button>}<button className="primary-btn" onClick={() => step === 2 ? finish() : setStep(step + 1)}>{step === 2 ? 'Show my opportunities' : 'Continue'} <ArrowRight size={16} /></button></div></div><p className="onboard-foot">You can update your preferences anytime in Profile.</p></main>}
